chore: must be pnpm
umijs/father-next pull request #39
Opened 2022-07-07 15:57 UTC by txp1035

2022-07-07 16:02 UTC, txp1035 commented
改npm ci就报错，上回是14.x版本，排查中

2022-07-08 03:56 UTC, txp1035 commented
![image](https://user-images.githubusercontent.com/9554297/177913971-3a59626e-c964-4920-97c8-16ae99c9e6b3.png)

2022-07-08 06:21 UTC, PeachScript requested changes

2022-07-08 06:21 UTC, PeachScript commented on package.json
> +    "preinstall": "esno scripts/preinstall.ts",
写 Contributing Guide 里就行了吧，这个 hook 会在用户安装 father 4 的时候也运行

2022-07-08 07:15 UTC, txp1035 commented on package.json
> +    "preinstall": "esno scripts/preinstall.ts",
你说的我问题我没考虑到，我去测试了下
![image](https://user-images.githubusercontent.com/9554297/177937999-4904b538-fc2c-409f-a9a9-5a2de4ffcff0.png)

2022-07-08 07:16 UTC, txp1035 commented on package.json
> +    "preinstall": "esno scripts/preinstall.ts",
![image](https://user-images.githubusercontent.com/9554297/177938251-49809f6f-780a-4882-8ae8-cbbfbbaf151e.png)

2022-07-08 08:16 UTC, PeachScript commented on package.json
> +    "preinstall": "esno scripts/preinstall.ts",
推测是 npm v7 有特殊变化，可以换几个包管理试下，以及 npm v7 以下的版本

2022-07-19 08:58 UTC, PeachScript commented
还是在 CONTRIBUTING.md 说明吧，closed

2022-07-19 08:58 UTC, closed without merging